version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.15.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  mcp_llm:
    image: mcp-server/mcp-llm:latest
    container_name: mcp-llm
    build:
      context: .
      dockerfile: mcp_llm_service/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - mcp_llm_service/.env

  mcp_rag:
    image: mcp-server/mcp-rag:latest
    container_name: mcp-rag
    build:
      context: .
      dockerfile: mcp_rag_server/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - mcp_rag_server/.env
    depends_on:
      - qdrant
      - mcp_llm

  slack_agent:
    image: mcp-server/slack-agent:latest
    container_name: slack-agent
    build:
      context: .
      dockerfile: slack_agent/Dockerfile
    env_file:
      - slack_agent/.env
    depends_on:
      - mcp_rag

volumes:
  qdrant_data:
